### ISSUE TITLE
Добавить геометрию в Movable

### ISSUE THREAD

**Issue by GarsiaAlex** [GarsiaAlex/Angry_penguin#1]
https://github.com/GarsiaAlex/Angry_penguin/blob/a13713040487e38020a8c16b90798482facb4741/angryPenguin/Movable.h#L10

**Comment by vixfwis** [comment]
поиск столкновений реализован без геометрии, соответствующий код `getMovePoint` удален

517c57285e4da5efab90f4b649d44575a2953d0f
