### ISSUE TITLE
Реализовать столкновения с Star

### ISSUE THREAD

**Issue by GarsiaAlex** [GarsiaAlex/Angry_penguin#2]
Столкновение вызывает метод игрока - добавление очков. Смотрите где лучше реализовать: Player или Map.

**Comment by AndyJoey** [comment]
Реализовано в e71cd43

**Comment by GarsiaAlex** [comment]
Оно должно адекватно добавлять очки, а не за каждое повторение основного цикла.

**Comment by AndyJoey** [comment]
ПОФИКШЕНО!!!
