### ISSUE TITLE
Прокрутка карты.

### ISSUE THREAD

**Issue by GarsiaAlex** [GarsiaAlex/Angry_penguin#6]
Когда игрок движется вправо область видимости карты должна сдвигаться. Возможности двинуться назад не должно быть.

**Comment by vixfwis** [comment]
реализовано в https://github.com/GarsiaAlex/Angry_penguin/commit/372b5d7a84df30bd843706173c232076888da59d#diff-7c7f3533e0df6d0f1eaf0ba914d9ca7dR63, после прохождения центра окна камера следует за игроком, обратно сдвинуть камеру нельзя
